name: ${oc.env:SHARE_RES_DIR}/models/qwen/Qwen2.5-1.5B-Instruct
class_name: Qwen2ForCausalLM
tokenizer_class: Qwen2Tokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/qwen/Qwen2.5-1.5B-Instruct
inner_params:
- model.layers.23.mlp.gate_proj.weight
- model.layers.23.mlp.up_proj.weight
- model.layers.23.mlp.down_proj.weight
- model.layers.24.mlp.gate_proj.weight
- model.layers.24.mlp.up_proj.weight
- model.layers.24.mlp.down_proj.weight
- model.layers.25.mlp.gate_proj.weight
- model.layers.25.mlp.up_proj.weight
- model.layers.25.mlp.down_proj.weight
- model.layers.26.mlp.gate_proj.weight
- model.layers.26.mlp.up_proj.weight
- model.layers.26.mlp.down_proj.weight
- model.layers.27.mlp.gate_proj.weight
- model.layers.27.mlp.up_proj.weight
- model.layers.27.mlp.down_proj.weight